export type TagVariant =
  | "three"
  | "websockets"
  | "react"
  | "redis"
  | "gray"
  | "html"
  | "css"
  | "javascript"
  | "node"
  | "next"
  | "kubernetes"
  | "postgresql"
  | "ogl"
  | "glsl"
  | "python"
  | "fastapi"
  | "rag"
  | "neo4j"
  | "wechat"
  | "minio"
  | "automation"
  | "fastgpt"
  | "llm"
  | "docker";

export const tagLabels = {
  three: "Three.js",
  websockets: "WebSockets",
  react: "React",
  redis: "Redis",
  gray: "Gray",
  html: "HTML",
  css: "CSS",
  javascript: "JavaScript",
  node: "Node.js",
  next: "Next.js",
  kubernetes: "Kubernetes",
  postgresql: "PostgreSQL",
  ogl: "OGL.js",
  glsl: "GLSL",
  python: "Python",
  fastapi: "FastAPI",
  rag: "RAG",
  neo4j: "Neo4j",
  wechat: "WeChat",
  minio: "MinIO",
  automation: "Automation",
  fastgpt: "FastGPT",
  llm: "LLM",
  docker: "Docker",
} as const satisfies Record<TagVariant, string>;
