import type { ProjectContent } from "../../types";

export default {
  title: "Step1X-3D · ARM64 Server Deployment",
  theme: "light",
  tags: ["python", "docker", "automation"],
  live: "/notes/step1x-3d-arm64-deployment.html",
  description:
    "A containerized StepFun Step1X-3D deployment on a remote NVIDIA GB10 ARM64 server, providing an end-to-end pipeline from a single image to geometry and textured 3D models.<br/><br/>The work covers CUDA 13 compatibility, native ARM64 extension builds, local loading of 100+ GB of model assets, Gradio serving, SSH tunneling, and safe public documentation.",
  components: [
    {
      type: "media",
      props: {
        type: "image",
        src: "/notes/images/step1x-3d-arm64-deployment/generation-result.webp",
        alt: "Step1X-3D textured and geometry results generated from one image",
        caption: "Textured and geometry models generated from one image",
      },
    },
    {
      type: "text",
      props: {
        title: "Deployment path",
        text: "The NVIDIA PyTorch container preserves the CUDA/PyTorch baseline required by GB10. nvdiffrast, PyTorch3D, and project-specific extensions are compiled natively on ARM64, while Step1X, CLIP, DINOv2, SDXL, VAE, BiRefNet, and U2Net are loaded entirely from local storage.",
      },
    },
    {
      type: "list",
      props: {
        title: "Engineering outcomes",
        size: "lg",
        items: [
          "Resolved missing ARM64 CUDA wheels, CuPy runtime mismatches, and required graphics system libraries.",
          "Validated both the Gradio interface and Python API, including geometry and textured GLB downloads.",
          "Published a reproducible deployment note with public addresses, host details, key paths, and local directories sanitized.",
        ],
      },
    },
    {
      type: "media",
      props: {
        type: "image",
        src: "/notes/images/step1x-3d-arm64-deployment/gradio-api.webp",
        alt: "Step1X-3D Gradio API documentation",
        caption: "Python API instructions generated by Gradio",
      },
    },
  ],
} as const satisfies ProjectContent;
